name: Generate Sitemap

on:
  # Run on every push to your main branch
  push:
    branches:
      - main # Or 'master' if that is your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          # This is the customized URL for your website
          base-url-path: https://chiinthedesert.github.io/blog-cua-chi

      - name: Commit and push sitemap
        run: |
          git config --global user.name 'Sitemap Bot'
          git config --global user.email 'sitemap-bot@users.noreply.github.com'
          git add sitemap.xml
          # Commit only if there are changes to the sitemap
          if ! git diff --staged --quiet; then
            git commit -m "Automated: Generate sitemap.xml"
            git push
          else
            echo "No changes to sitemap.xml"
          fi
